"""
Sends text to the Ray Serve embedding endpoint via async HTTP requests.
Supports two operations: query embedding (for search) and document embedding (for indexing).
Uses HTTPX async client for non-blocking API calls.
Returns vector embeddings generated by the embedding model.
"""


import httpx
from typing import List
from services.api.app.config import settings

class RayEmbeddingClient:
    """
    Async client for the Ray Serve Embedding Service.
    Sends text to the embedding endpoint and returns vectors.
    """

    async def embed_query(self, text: str) -> List[float]:
        async with httpx.AsyncClient() as client:
            response = await client.post(
                settings.RAY_EMBEDDING_ENDPOINT,
                json={
                    "text": text, 
                    "task_type": "query"
                } 
            )

            response.raise_for_status()
            return response.json()["embedding"][0]

    async def embed_documents(self, text: List[str]) -> List[List[float]]:
        """
        Generate embeddings for multiple documents.
        Used during ingestion.
        """
        async with httpx.AsyncClient(timeout=60.0) as client:
            response = await client.post(
                settings.RAY_EMBEDDING_ENDPOINT,
                json = {
                    "text": text, 
                    "task_type": "document"
                }
            )

            response.raise_for_status()
            return response.json()['embeddings']

# Global Instance (Managed by Lifespan in main.py)
embed_client = RayEmbeddingClient()


