"""
Sends text to the Ray Serve embedding endpoint via async HTTP requests.
Supports two operations: query embedding (for search) and document embedding (for indexing).
Uses a persistent HTTPX async client for non-blocking, connection-reusing API calls.
Returns vector embeddings generated by the embedding model.
"""

import httpx
from services.api.app.config import settings


class RayEmbeddingClient:
    """
    Async client for the Ray Serve Embedding Service.
    Maintains a persistent HTTP connection for efficient repeated calls.
    Managed by FastAPI lifespan via start() and close().
    """

    def __init__(self):
        self._client: httpx.AsyncClient | None = None

    async def start(self):
        """Initialize the persistent HTTP client. Called on app startup."""
        self._client = httpx.AsyncClient(timeout=60.0)

    async def close(self):
        """Close the persistent HTTP client. Called on app shutdown."""
        if self._client:
            await self._client.aclose()

    def _get_client(self) -> httpx.AsyncClient:
        if self._client is None:
            raise RuntimeError("EmbeddingClient not started. Call start() first.")
        return self._client

    async def embed_query(self, text: str) -> list[float]:
        """Generate embedding for a single query. Used during search."""
        response = await self._get_client().post(
            settings.RAY_EMBEDDING_ENDPOINT,
            json={"text": text, "task_type": "query"}
        )
        response.raise_for_status()
        return response.json()["embedding"][0]

    async def embed_documents(self, texts: list[str]) -> list[list[float]]:
        """Generate embeddings for multiple documents. Used during ingestion."""
        response = await self._get_client().post(
            settings.RAY_EMBEDDING_ENDPOINT,
            json={"text": texts, "task_type": "document"}
        )
        response.raise_for_status()
        return response.json()["embeddings"]


# Global Instance (Managed by Lifespan in main.py)
embed_client = RayEmbeddingClient()